---
networks:
  docker_test_rigs:
    enable_ipv6: true
    driver: bridge
    name: docker_test_rigs
    ipam:
      driver: default
      config:
        - subnet: fc00:cafe:cafe::/64
          gateway: fc00:cafe:cafe::1

services:
  archlinux:
    image: archlinux
    hostname: archlinux
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  archlinux-puppet-lint:
    build: ./conf/archlinux/puppet-lint
    hostname: archlinux-puppet-lint
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  archlinux-vim:
    build: ./conf/archlinux/vim
    hostname: archlinux-vim
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
      - ~/.vimrc:/root/.vimrc
      - ~/.vim:/root/.vim
    entrypoint: /entrypoint.sh

  centos7:
    build: ./conf/centos/7
    hostname: centos7
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  centos7-puppet:
    build: ./conf/centos/7/puppet
    hostname: centos7-puppet
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  centos7-puppet_rpm_gpgkey_issue:
    build: ./conf/centos/7/puppet_rpm_gpgkey_issue
    hostname: centos7-puppet_rpm_gpgkey_issue
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  rockylinux9:
    image: rockylinux9
    hostname: rockylinux9
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  rockylinux9-puppet_rpm_gpgkey_issue:
    build: ./conf/rockylinux/9/puppet_rpm_gpgkey_issue
    hostname: rockylinux9-puppet_rpm_gpgkey_issue
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu1204:
    build: ./conf/ubuntu/1204
    hostname: ubuntu1204
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2004:
    image: ubuntu:20.04
    hostname: ubuntu2004
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2004-puppet:
    build: ./conf/ubuntu/2004/puppet
    hostname: ubuntu2004-puppet
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2004-puppet-lint:
    build: ./conf/ubuntu/2004/puppet-lint
    hostname: ubuntu2004-puppet-lint
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2004-elastic-agent:
    build: ./conf/ubuntu/2004/elastic-agent
    hostname: ubuntu2004-elastic-agent
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  # Note v6 doesn't seem to work for iptables
  ubuntu2004-puppet-iptables:
    build: ./conf/ubuntu/2004/puppet-iptables
    hostname: ubuntu2004-puppet-iptables
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh
    cap_add:
      - NET_ADMIN

  ubuntu2204:
    image: ubuntu:22.04
    hostname: ubuntu2204
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2204-apache:
    build: ./conf/ubuntu/2204/apache
    hostname: ubuntu2204-apache
    volumes:
      - ./tmp:/mnt/tmp

  ubuntu2204-owasp:
    build: ./conf/ubuntu/2204/owasp
    hostname: ubuntu2204-owasp
    volumes:
      - ./tmp:/mnt/tmp


  ubuntu2204-puppet_rpm_gpgkey_issue:
    build: ./conf/ubuntu/2204/puppet_rpm_gpgkey_issue
    hostname: ubuntu2204-puppet_rpm_gpgkey_issue
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2404:
    image: ubuntu:24.04
    hostname: ubuntu2404
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2404-puppet:
    build: ./conf/ubuntu/2404/puppet
    hostname: ubuntu2404-puppet
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  ubuntu2404-puppet7-iptables:
    build: ./conf/ubuntu/2404/puppet7-iptables
    hostname: ubuntu2404-puppet7-iptables
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh
    cap_add:
      - NET_ADMIN
    networks:
      docker_test_rigs:
        ipv6_address: fc00:cafe:cafe::7

  ubuntu2404-puppet8-iptables:
    build: ./conf/ubuntu/2404/puppet8-iptables
    hostname: ubuntu2404-puppet8-iptables
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh
    cap_add:
      - NET_ADMIN
    networks:
      docker_test_rigs:
        ipv6_address: fc00:cafe:cafe::8

  ubuntu2404-nftables:
    build: ./conf/ubuntu/2404/nftables
    hostname: ubuntu2404-nftables
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh
    cap_add:
      - NET_ADMIN
    networks:
      docker_test_rigs:
        ipv6_address: fc00:cafe:cafe::9

  # Connect via browser (port 8006) or RDP to the containers IP for a GUI
  windows11:
    image: dockurr/windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure
