---
include:
  - conf/archlinux/archlinux.yaml
  - conf/ubuntu/ubuntu.yaml

networks:
  docker_test_rigs:
    enable_ipv6: true
    driver: bridge
    name: docker_test_rigs
    ipam:
      driver: default
      config:
        - subnet: fc00:cafe:cafe::/64
          gateway: fc00:cafe:cafe::1
        - subnet: 172.19.9.0/24
          gateway: 172.19.9.1

services:
  centos7:
    build: ./conf/centos/7
    hostname: centos7
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  centos7-puppet:
    build: ./conf/centos/7/puppet
    hostname: centos7-puppet
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  centos7-puppet_rpm_gpgkey_issue:
    build: ./conf/centos/7/puppet_rpm_gpgkey_issue
    hostname: centos7-puppet_rpm_gpgkey_issue
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  rockylinux9:
    image: rockylinux9
    hostname: rockylinux9
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  rockylinux9-puppet_rpm_gpgkey_issue:
    build: ./conf/rockylinux/9/puppet_rpm_gpgkey_issue
    hostname: rockylinux9-puppet_rpm_gpgkey_issue
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./tmp:/mnt/tmp
    entrypoint: /entrypoint.sh

  # Connect via browser (port 8006) or RDP to the containers IP for a GUI
  windows11:
    image: dockurr/windows
    environment:
      VERSION: "win11"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    stop_grace_period: 2m
    restart: on-failure

  tomcat9.0.104-jre17:
    build: ./conf/tomcat/9.0.104-jre17
    hostname: tomcat9.0.104-jre17
    post_start:
      - command: bash -c 'echo -e "\nTomcat http://$(hostname -i):8080/manager/html admin/admin\n"'

  tomcat10.1.41-jre17:
    build: ./conf/tomcat/10.1.41-jre17
    hostname: tomcat10.1.41-jre17
    post_start:
      - command: bash -c 'echo -e "\nTomcat http://$(hostname -i):8080/manager/html admin/admin\n"'
