---
services:
  archlinux:
    image: archlinux
    hostname: archlinux
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  archlinux-puppet-lint:
    build: ./conf/archlinux/puppet-lint
    hostname: archlinux-puppet-lint
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  archlinux-vim:
    build: ./conf/archlinux/vim
    hostname: archlinux-vim
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ~/.vimrc:/root/.vimrc
      - ~/.vim:/root/.vim
    entrypoint: /entrypoint.sh

  ubuntu1204:
    build: ./conf/ubuntu/1204
    hostname: ubuntu1204
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  ubuntu2004:
    image: ubuntu:20.04
    hostname: ubuntu2004
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  ubuntu2004-puppet-lint:
    build: ./conf/ubuntu/2004/puppet-lint
    hostname: ubuntu2004-puppet-lint
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  ubuntu2004-elastic-agent:
    build: ./conf/ubuntu/2004/elastic-agent
    hostname: ubuntu2004-elastic-agent
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh

  ubuntu2204:
    image: ubuntu:22.04
    hostname: ubuntu2204
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
